name: time_tracker_ter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  csv: ^5.0.2
  cupertino_icons: ^0.1.2
  drag_and_drop_lists: ^0.3.3
  eva_icons_flutter: ^3.1.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_slidable: ^2.0.0
  flutter_svg: ^1.1.6
  fluttertoast: ^8.2.1
  grouped_list: ^5.1.2
  http: ^0.13.4
  intl: ^0.18.0
  mailer: ^6.0.1
  page_transition: ^2.0.9
  path: ^1.8.2
  path_provider: ^2.0.14
  pie_chart: ^5.3.2
  shared_preferences: ^2.0.20
  sqflite: ^2.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg
    - assets/icons/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf

